<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>44d33a27-fb9e-4197-b81b-9493411945a1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\api\Peritus.Api\Peritus.Api.csproj"/>
    <ProjectReference Include="..\..\modules\Peritus.Identity.Migrator\Peritus.Identity.Migrator.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost"/>
    <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
    <PackageReference Include="Aspire.Hosting.Valkey"/>
  </ItemGroup>

</Project>
