<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Peritus.Results\Peritus.Results.csproj"/>
    <ProjectReference Include="..\Peritus.Types\Peritus.Types.csproj"/>
  </ItemGroup>

</Project>
