<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Peritus.IntegrationTests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
    <PackageReference Include="Aspire.Hosting.Testing"/>
    <PackageReference Include="Aspire.Hosting.Valkey"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing"/>
    <PackageReference Include="Refit"/>
    <PackageReference Include="xunit.analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JetBrains.Annotations"/>
    <PackageReference Include="xunit.v3.assert"/>
    <PackageReference Include="xunit.v3.extensibility.core"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\apps\Peritus.Api\Peritus.Api.csproj"/>
    <ProjectReference Include="..\..\..\src\Peritus.AppHost\Peritus.AppHost.csproj"/>
  </ItemGroup>

</Project>
